apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-db
  labels:
    app: sheep-dog
    component: sheep-dog-db
spec:
  selector:
    matchLabels:
      component: sheep-dog-db
  template:
    metadata:
      labels:
        app: sheep-dog
        component: sheep-dog-db
    spec:
      containers:
        - name: sheep-dog-db
          image: "{{ .Values.images.db.repository }}:{{ .Values.images.db.tag }}"
          imagePullPolicy: {{ .Values.images.db.pullPolicy | quote }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-volume
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: sheep-dog-db-pvc
