{{- if .Values.graphwalkerUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: graphwalker-ui
  labels:
    app: sheep-dog
    component: graphwalker-ui
spec:
  selector:
    component: graphwalker-ui
  ports:
    - name: graphwalker-ui
      port: 80
      targetPort: 9090
  type: ClusterIP
{{- end }}
