{{- if .Values.graphmlApi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheep-dog-graphml-api-svc
  labels:
    app: sheep-dog
    component: sheep-dog-graphml-api-svc
spec:
  selector:
    matchLabels:
      component: sheep-dog-graphml-api-svc
  template:
    metadata:
      labels:
        app: sheep-dog
        component: sheep-dog-graphml-api-svc
    spec:
      containers:
        - name: sheep-dog-graphml-api-svc
          image: "{{ .Values.images.graphmlApi.repository }}:{{ .Values.images.graphmlApi.tag }}"
          imagePullPolicy: {{ .Values.images.graphmlApi.pullPolicy | quote }}
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g -Xms256m"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_PATH
              value: "/logs"
            - name: SHEEPDOG_REPO_BASEDIR
              value: "/repo/"
            - name: SPRING_ARTEMIS_HOST
              value: sheep-dog-amq
            - name: SPRING_ARTEMIS_PORT
              value: "61616"
            - name: SPRING_ARTEMIS_USER
              value: artemis
            - name: SPRING_ARTEMIS_PASSWORD
              value: artemis
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /sheep-dog-graphml-api-svc/actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
            - name: repo-volume
              mountPath: /repo
          resources:
            limits:
              memory: "1536Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: sheep-dog-graphml-api-svc-pvc
        - name: repo-volume
          persistentVolumeClaim:
            claimName: sheep-dog-repo-pvc
{{- end }}
