apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheep-dog-repo-pvc
  labels:
    app: sheep-dog
    component: sheep-dog-repo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvcStorageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.repo.pvcSize | quote }}
