{{- if .Values.graphwalkerUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphwalker-ui
  labels:
    app: graphwalker
    component: graphwalker-ui
spec:
  selector:
    matchLabels:
      component: graphwalker-ui
  template:
    metadata:
      labels:
        app: graphwalker
        component: graphwalker-ui
    spec:
      containers:
        - name: graphwalker-ui
          image: "{{ .Values.images.graphwalkerUi.repository }}:{{ .Values.images.graphwalkerUi.tag }}"
          imagePullPolicy: {{ .Values.images.graphwalkerUi.pullPolicy | quote }}
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g -Xms256m"
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /studio.html
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /studio.html
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
{{- end }}
