{{- if .Values.graphwalkerSvc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: graphwalker-svc
  labels:
    app: graphwalker
    component: graphwalker-svc
spec:
  selector:
    component: graphwalker-svc
  ports:
    - name: graphwalker-svc
      port: 80
      targetPort: 8080
  type: ClusterIP
{{- end }}
