name: Deploy with Create

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace (also used as EKS stack suffix)'
        required: true
        default: 'prod'

jobs:
  setup-cluster:
    uses: ./.github/workflows/setup-cluster.yml
    with:
      namespace: ${{ inputs.namespace }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  setup-namespace:
    needs: setup-cluster
    uses: ./.github/workflows/setup-namespace.yml
    with:
      namespace: ${{ inputs.namespace }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  smoke-test:
    needs: setup-namespace
    uses: ./.github/workflows/smoke-test.yml
    with:
      host: ${{ needs.setup-namespace.outputs.service_url }}

  teardown-namespace:
    needs: smoke-test
    uses: ./.github/workflows/teardown-namespace.yml
    with:
      namespace: ${{ inputs.namespace }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  teardown-cluster:
    needs: teardown-namespace
    uses: ./.github/workflows/teardown-cluster.yml
    with:
      namespace: ${{ inputs.namespace }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
