name: E2E Test

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the stack name'
        required: true
        default: '1'

jobs:
  setup-eks:
    uses: ./.github/workflows/setup-eks.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  setup-namespace:
    needs: setup-eks
    uses: ./.github/workflows/setup-namespace.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  forward-engineer:
    needs: setup-namespace
    uses: ./.github/workflows/forward-engineer.yml
    with:
      host: ${{ needs.setup-namespace.outputs.service_url }}

  teardown-namespace:
    needs: forward-engineer
    uses: ./.github/workflows/teardown-namespace.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  teardown-eks:
    needs: teardown-namespace
    uses: ./.github/workflows/teardown-eks.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
