name: E2E Test

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the stack name'
        required: true
        default: '1'

jobs:
  setup-stack:
    uses: ./.github/workflows/setup-stack.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  setup-cluster:
    needs: setup-stack
    uses: ./.github/workflows/setup-cluster.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  forward-engineer:
    needs: setup-cluster
    runs-on: ubuntu-latest
    env:
      HOST: ${{ needs.setup-cluster.outputs.service_url }}
    steps:
      - name: Checkout sheep-dog-specs
        uses: actions/checkout@v4
        with:
          repository: farhan5248/sheep-dog-specs
          path: sheep-dog-specs
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Forward engineer
        working-directory: sheep-dog-specs/sheep-dog-features
        run: |
          mvn clean
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="asciidoc-api" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="cucumber-gen" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="grammar" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="svc-maven-plugin" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="asciidoc-api-svc" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="cucumber-gen-svc" -Dhost="$HOST"
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="mcp-svc" -Dhost="$HOST"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  teardown-cluster:
    needs: forward-engineer
    uses: ./.github/workflows/teardown-cluster.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  teardown-stack:
    needs: teardown-cluster
    uses: ./.github/workflows/teardown-stack.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
