name: E2E Test

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the stack name'
        required: true
        default: '1'

jobs:
  setup-stack:
    uses: ./.github/workflows/setup-stack.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  setup-cluster:
    needs: setup-stack
    uses: ./.github/workflows/setup-cluster.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  forward-engineer:
    needs: setup-cluster
    runs-on: [farhan5248-runners]
    permissions:
      contents: read
      packages: read
    env:
      HOST: ${{ needs.setup-cluster.outputs.service_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Forward engineer
        working-directory: sheep-dog
        run: |
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="svc-maven-plugin" -Dhost="$HOST"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  teardown-cluster:
    needs: forward-engineer
    uses: ./.github/workflows/teardown-cluster.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  teardown-stack:
    needs: teardown-cluster
    uses: ./.github/workflows/teardown-stack.yml
    with:
      suffix: ${{ inputs.suffix }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
