name: Forward Engineer

on:
  workflow_call:
    inputs:
      host:
        description: 'Host parameter for Maven'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      host:
        description: 'Host parameter for Maven'
        required: true
        default: 'localhost'

jobs:
  forward-engineer:
    runs-on: [farhan5248-runners]
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout sheep-dog-specs
        uses: actions/checkout@v4
        with:
          repository: farhan5248/sheep-dog-specs
      - name: Set up JDK 21
        run: echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" >> $GITHUB_ENV
      - name: Forward engineer
        working-directory: sheep-dog-features
        run: |
          mvn org.farhan:sheep-dog-svc-maven-plugin:asciidoctor-to-uml -Dtags="svc-maven-plugin" -Dhost="${{ inputs.host }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
