name: NPM Snapshot

on:
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        type: choice
        options:
          - sheep-dog-vscode-plugin
jobs:
  build:
    runs-on: [farhan5248-runners]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: ./${{ inputs.project }}
      run: npm install
    - name: Package extension
      working-directory: ./${{ inputs.project }}
      run: |
        mkdir -p build
        npx vsce package --out build/${{ inputs.project }}.vsix
